### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [peteboyd/lammps_interface#35]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.1.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary lammps-interface -w /tmp/ext lammps-interface==0.1.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting lammps-interface==0.1.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/a43/e5db5b36c7613/lammps-interface-0.1.2.tar.gz (105 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-1c5jig3n/lammps-interface/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-1c5jig3n/lammps-interface/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-1c5jig3n/lammps-interface/pip-egg-info
         cwd: /tmp/pip-wheel-1c5jig3n/lammps-interface/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-1c5jig3n/lammps-interface/setup.py", line 3, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by ltalirz** [comment]
thanks for the heads up @thatch -  fixed in #36 .
Once @peteboyd gets to have a look at some of the open issues, we'll make a new release .
