### ISSUE TITLE
error running test

### ISSUE THREAD

**Issue by alberto-fraccarollo-eleva** [peteboyd/lammps_interface#59]
Hi, 
I installed last version of lammps-interface present in github repository, but running the example I receive this error:

Traceback (most recent call last):
  File "/usr/local/bin/lammps-interface", line 33, in <module>
    sys.exit(load_entry_point('lammps-interface==0+unknown', 'console_scripts', 'lammps-interface')())
  File "/usr/local/bin/lammps-interface", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/cli.py", line 3, in <module>
    from .lammps_main import LammpsSimulation
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/lammps_main.py", line 11, in <module>
    from . import ForceFields
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/ForceFields.py", line 25, in <module>
    from .Molecules import *
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/Molecules.py", line 7, in <module>
    from .structure_data import MolecularGraph
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/structure_data.py", line 14, in <module>
    from .mof_sbus import InorganicCluster, OrganicCluster
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/mof_sbus.py", line 1553, in <module>
    add_distance_matrix(InorganicCluster['Cu']['Cu Paddlewheel'])
  File "/usr/local/lib/python3.10/dist-packages/lammps_interface-0+unknown-py3.10.egg/lammps_interface/mof_sbus.py", line 11, in add_distance_matrix
    if(float('.'.join(nx.__version__.split('.')[:2])) >= 2.0):
ValueError: could not convert string to float: '3.0rc1'

How could I [fix.it](http://fix.it/)?
Regards

Alberto

**Comment by ltalirz** [comment]
Hi Alberto,

looks like the networkx version you are using has a version that lammps interface does not understand. Perhaps try installing it with "networkx<3"?

In any case, I am not using lammps-interface at the moment (and haven't done so in a while).
This package is looking for a new maintainer (in my last email exchange with Pete Boyd, the original author of this package also expressed this intention).

@peteboyd Shall we add a note to the README about this?

**Comment by ltalirz** [comment]
I suspect my last pull request will have fixed this https://github.com/peteboyd/lammps_interface/pull/60

You can try installing from source and let me know whether it works
